### ISSUE TITLE
Not loading babel plugins

### ISSUE THREAD

**Issue by DavidBriglio** [ctumolosus/jsdoc-babel#106]
Hello, I am trying to use this package to allow support for optional chaining `var1?.var2` in my documentation. I cannot get this package to load `@babel/plugin-proposal-optional-chaining`. I have a `.babelrc` file with this plugin listed, but I also tried to put this in the jsdoc configuration file without success.

Is this an issue or is there something else I would have to do?

Versions:
@babel/core 7.4.4
jsdoc 3.6.5

**Comment by ctumolosus** [comment]
I added optional chaining to the [`/example`](https://github.com/ctumolosus/jsdoc-babel/tree/master/example) directory and didn't run into any issues. Can you share a link where I can reproduce? What is the error that you are seeing?

**Comment by DavidBriglio** [comment]
I don't believe the error I am getting is from this plugin. I was trying to use `better-docs` for the react `@component` tag, and it was breaking when trying to include optional chaining. I thought that this plugin would help, but I believe the issue is with that library and not this one.
