### ISSUE TITLE
[BUG] jsdoc-babel removing my jsdoc comments

### ISSUE THREAD

**Issue by PythonCreator27** [ctumolosus/jsdoc-babel#107]
For some reason, `jsdoc-babel` is removing my jsdoc comments. I know that babel is not at fault, because running babel keeps the comments when compiled. Is there a way to fix this without a hacky fix?

**Comment by PythonCreator27** [comment]
Here is my jsdoc config:
```json
{
    "source": {
        "includePattern": "\\.ts$",
        "excludePattern": "\\.(test|spec).ts"
    },
    "plugins": ["plugins/markdown", "node_modules/jsdoc-babel"],
    "babel": {
        "extensions": ["ts"]
    }
}
```

**Comment by ctumolosus** [comment]
Can you share a minimal repro? E.g. Fork the project, add a directory to `/examples` with repro, and share your fork here. Use the existing examples as guidance.

**Comment by advaiyalad** [comment]
Never mind. The  problem is solved. I had to use the `--extensions` flag for jsdoc, I think.
