### ISSUE TITLE
Stage 0 not working

### ISSUE THREAD

**Issue by resistdesign** [ctumolosus/jsdoc-babel#2]
I set stage to 0 in the jsdoc babel options but it's still failing on static member declarations.

```
SyntaxError: unknown: Unexpected token (4:24)
  2 | 
  3 | export default class CommandError extends ErrorClass {
> 4 |   static MESSAGE_PREFIX = 'There was an error while executing the command: ';
    |                         ^
```

NOTE: The class it's parsing compiles/transpiles without error.

**Comment by vitosamson** [comment]
Ran into this issue with es7 decorators. You can pass an array of optional transformers to enable in the babel config in your jsdoc config:
```
{
  "babel": {
    "optional": ["es7.classProperties"]
  }
}
```
run `babel --help` to see the list of optional transformers. https://github.com/babel/babel.github.io/blob/862b43db93e48762671267034a50c30c00e433e2/docs/usage/options.md#options
