### ISSUE TITLE
Use .babelrc file?

### ISSUE THREAD

**Issue by idmontie** [ctumolosus/jsdoc-babel#35]
Is it possible to have this use my pre-existing `.babelrc` file for my project?

I tried just having:

```
{
    "plugins": ["node_modules/jsdoc-babel"]
}
```

But using jsdoc-to-markdown wasn't able to parse my file since I am using some stage-2 transforms. When I copied my babelrc into my jsdoc configuration, it worked.

**Comment by ctumolosus** [comment]
Hi, thanks for your input. I guess I was hoping that was something `require('babel-core').transform` did behind the scenes. I'm a little busy with work-related things, but when I have the time I will look into reading options from `.babelrc` file.

**Comment by ctumolosus** [comment]
Hey @idmontie,

I just published version `0.3.0` and it should resolve `.babelrc` files in your project. 

As I suspected, the Babel transformer attempts to find one but it did not have enough information to resolve it.

By the way, it looks like as of 3.4.0 JSDoc supports ES6 and JSX (see [CHANGELOG](https://github.com/jsdoc3/jsdoc/blob/master/CHANGES.md)). 

I'm closing this issue for now. Feel free to reopen if you have any issues.

**Comment by idmontie** [comment]
Thanks for quickly looking into this!
