### ISSUE TITLE
It shows incorrect line numbers

### ISSUE THREAD

**Issue by desaroger** [ctumolosus/jsdoc-babel#70]
Hi! I am using jsdoc-babel in order to build an api docs.

Everything works fine, it works with ES6 features without troubles, but has one problem: In the generated website (using nimani theme) it says the line numbers, but they are incorrect. I assume these are the numbers of the code parsed through babel, as all the lines it shows are greater than the original ones.

I tried to find some solution as everyone using this library must be faced this issue, but I can't find nothing, so I am sure I am doing something wrong.

I tried adding `sourceMaps = "inline"` to the .jsdoc.json file inside 'babel' property, to check if the sourceMaps can help with getting the correct line, but not worked.

Thanks in advance!

**Versions:**

- jsdoc: ^3.4.3
- jsdoc-babel: ^0.3.0

**.jsdoc.json**:
```json
{
  "tags": {
    "allowUnknownTags": true,
    "dictionaries": ["jsdoc"]
  },
  "source": {
    "include": ["src", "package.json"],
    "includePattern": ".js$",
    "excludePattern": "(node_modules/|docs)"
  },
  "plugins": [
    "node_modules/jsdoc-babel"
  ],
  "babel": {
    "sourceMaps": "inline"
  },
  "templates": {
    "cleverLinks": false,
    "monospaceLinks": true,
    "useLongnameInNav": false
  },
  "opts": {
    "destination": "./docs/",
    "encoding": "utf8",
    "private": true,
    "recurse": true,
    "template": "./node_modules/minami"
  }
}
```

**.babelrc:**
```json
{
    "presets": [ "es2015" ]
}
```

**script:**

```
jsdoc ./src/index.js --configure .jsdoc.json
```

**Showing the line of the method "fromRaw":**
![screenshot from 2017-03-26 01-05-18](https://cloud.githubusercontent.com/assets/19184101/24327112/581ab9f0-11c0-11e7-8072-4848c143532b.png)

**That line in the source file:**
![screenshot from 2017-03-26 01-05-33](https://cloud.githubusercontent.com/assets/19184101/24327113/66d0589c-11c0-11e7-9054-d6dfe526f986.png)

As you can see, it says that method is in line 27 but actually the line of that method is 23. Every line it shows is always bigger by some lines compared to the real line, and as the lines number grows, bigger is the difference.

**Comment by ctumolosus** [comment]
Hi, thanks for the detailed report. Your initial assumption was correct. This module simply transpiles the code before it's piped into JSDoc. Incorrect line numbers in the output is one of the caveats of this process. I'm not sure if there is a way for me to retain the original source for JSDoc. I will try to look into that.

**Comment by eeve** [comment]
Is there new progress?

**Comment by ctumolosus** [comment]
I haven't had time to look into this yet, sorry.

**Comment by reyalpsirc** [comment]
Not sure if it helps but at least I get better results with `"retainLines": true` set on the .jsdoc.json

**Comment by ctumolosus** [comment]
By the way, it looks like JSDoc started using Babylon to parse JavaScript files from version 3.5.0, which provides better output results. You may not need to use this plugin unless your source code contains unsupported syntax that needs to be transformed before it is parsed by JSDoc.

**Comment by ctumolosus** [comment]
Fixed in https://github.com/ctumolosus/jsdoc-babel/pull/85
