### ISSUE TITLE
Unexpected token "="

### ISSUE THREAD

**Issue by ArtemiyDmtrvch** [ctumolosus/jsdoc-babel#88]
I have this code:
`class Class {
    a: string = "b"
}`
Without jsdoc-babel syntax error appears at ":".  But if I don't set the type, leaving just `a = "b"`, everything will work fine.
With jsdoc-babel syntax error appears at "=".
None of plugins and presets (babel-preset-react, babel-preset-latest, babel-plugin-transform-flow-strip-types) resolved my issue.

**Comment by ctumolosus** [comment]
Have you tried using the [`babel-plugin-transform-class-properties`](https://babeljs.io/docs/en/babel-plugin-transform-class-properties/)?

**Comment by ArtemiyDmtrvch** [comment]
@ctumolosus I've tried it right now and it resolved my issue. Thank you!
